version: '3.7'
services:

  # Plex | https://hub.docker.com/r/plexinc/pms-docker/
  plex:
    container_name: plex
    image:  linuxserver/plex
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=America/Santiago
      - PLEX_UID=0
      - PLEX_GUID=0
    volumes:
      - /opt/plex-docker/config:/config
      - /opt/plex-docker//transcode:/transcode
      - /mnt/multimedia:/mnt/multimedia
        
  
  # Sonarr | https://hub.docker.com/r/linuxserver/sonarr
  sonarr:
    container_name: sonarrv3
    image: linuxserver/sonarr:preview
    restart: unless-stopped
    networks:
      - media-stack
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Santiago
    volumes:
      - /opt/sonarrv3:/config
      - /mnt/multimedia:/mnt/multimedia
      - /mnt/download:/downloads
      - /mnt/multimedia/sonarr/Series:/tv
    ports:
      - 8989:8989
      
  # Radarr | https://hub.docker.com/r/linuxserver/radarr
  radarr:
    container_name: radarr
    image: linuxserver/radarr
    restart: unless-stopped
    networks:
      - media-stack
    environment:
      - PUID=1000
      - PGID=1004
      - TZ=America/Santiago
    volumes:
      - $PWD/radarr/config:/config
      - /mnt/nfs/movies:/movies
      - /mnt/nfs/downloads:/downloads
    ports:
      - 7878:7878

  # Tautulli | https://hub.docker.com/r/linuxserver/tautulli
  tautulli:
    image: linuxserver/tautulli
    container_name: tautulli
    restart: unless-stopped
    networks:
      - media-stack
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Santiago
    volumes:
      - /opt/tautulli/config:/config
      - /opt/plex-docker/config/Library/Application Support/Plex Media Server/Logs:/logs
    ports:
      - 8181:8181

networks:
  media-stack:
    name: media-stack
