version: '3.6'
services:

  # Plex | https://hub.docker.com/r/plexinc/pms-docker/
  plex:
    container_name: plex
    image:  linuxserver/plex
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=America/Santiago
      - PLEX_UID=0
      - PLEX_GUID=0
    volumes:
      - /opt/plex-docker/config:/config
      - /opt/plex-docker//transcode:/transcode
      - /mnt/multimedia:/mnt/multimedia
      - /mnt/download:/download
    ports:
      - 32400:32400
      - 3005:3005
      - 8324:8324
      - 32469:32469
        
  
  # Sonarr | https://hub.docker.com/r/linuxserver/sonarr
  sonarr:
    container_name: sonarrv3
    image: linuxserver/sonarr:preview
    restart: unless-stopped
    networks:
      - media-stack
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Santiago
    volumes:
      - /opt/sonarrv3:/config
      - /mnt/multimedia:/mnt/multimedia
      - /mnt/download:/downloads
      - /mnt/multimedia/sonarr/Series:/tv
    ports:
      - 8989:8989
      
  # Radarr | https://hub.docker.com/r/linuxserver/radarr
  radarr:
    container_name: radarr
    image: linuxserver/radarr:preview
    restart: unless-stopped
    networks:
      - media-stack
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Santiago
    volumes:
      - /opt/radarr-docker/config:/config
      - /mnt/multimedia/Movies:/movies
      - /mnt/download:/downloads
      - /mnt/multimedia:/mnt/multimedia
    ports:
      - 7878:7878

  # Tautulli | https://hub.docker.com/r/linuxserver/tautulli
  tautulli:
    image: linuxserver/tautulli
    container_name: tautulli
    restart: unless-stopped
    networks:
      - media-stack
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Santiago
    volumes:
      - /opt/tautulli/config:/config
      - /opt/plex-docker/config/Library/Application Support/Plex Media Server/Logs:/logs
    ports:
      - 8181:8181

  # Lidarr | https://hub.docker.com/r/linuxserver/lidarr
  lidarr:
    container_name: lidarr
    image: linuxserver/lidarr:latest
    restart: unless-stopped
    networks:
      - media-stack
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Santiago
    volumes:
      - /opt/lidarr:/config
      - /mnt/download:/downloads
      - /mnt/download:/mnt/download
      - /mnt/multimedia:/mnt/multimedia
    ports:
      - 8686:8686

  # Bazarr | https://hub.docker.com/r/linuxserver/bazarr
  bazarr:
    container_name: bazarr
    image: linuxserver/bazarr:latest
    restart: unless-stopped
    networks:
      - media-stack
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Santiago
    volumes:
      - /opt/bazarr:/config
      - /mnt/download:/downloads
      - /mnt/multimedia:/mnt/multimedia
    ports:
      - 6767:6767

# ouroboros | https://hub.docker.com/r/pyouroboros/ouroboros
  ouroboros:
    container_name: ouroboros
    image: pyouroboros/ouroboros:latest
    restart: unless-stopped
    networks:
      - media-stack
    environment:
      - PUID=0
      - PGID=0
      - LATEST=true
      - TZ=America/Santiago
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

# Jackett | https://hub.docker.com/r/linuxserver/jackett
  jackett:
    container_name: jackett
    image: linuxserver/jackett:latest
    restart: unless-stopped
    networks:
      - media-stack
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Santiago
    volumes:
      - /opt/jackett:/config
      - /mnt/download:/downloads
      - /mnt/multimedia:/mnt/multimedia
    ports:
      - 9117:9117

# deluge | https://hub.docker.com/r/linuxserver/deluge
  deluge:
    container_name: deluge
    image: linuxserver/deluge:latest
    restart: unless-stopped
    networks:
      - media-stack
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Santiago
    volumes:
      - /opt/deluge-docker:/config
      - /mnt/download:/downloads
      - /mnt/multimedia:/mnt/multimedia
    ports:
      - 8112:8112

# filebrowser | https://hub.docker.com/r/filebrowser/filebrowser
  filebrowser:
    container_name: filebrowser
    image: filebrowser/filebrowser:latest
    restart: unless-stopped
    networks:
      - media-stack
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Santiago
    volumes:
      - /opt/filebrowser:/data
      - /opt/filebrowser/database.db:/database.db
      - /mnt/multimedia:/srv
    ports:
      - 89:80

  heimdall:
    image: linuxserver/heimdall:latest
    container_name: heimdall
    networks:
      - media-stack
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Santiago
    volumes:
      - /opt/heimdall:/config
    ports:
      - 8280:80
      - 2143:443
    restart: unless-stopped

  proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: proxy-manager
    restart: always
    ports:
      - 88:80
      - 81:81
      - 8443:443
    volumes:
      - /opt/proxy-manager/config/config.json:/app/config/production.json
      - /opt/proxy-manager/data:/data
      - /opt/proxy-manager/letsencrypt:/etc/letsencrypt
    depends_on:
      - dbproxy
    networks:
      - media-stack
    environment:
    # if you want pretty colors in your docker logs:
    - FORCE_COLOR=1
    - TZ=America/Santiago
  dbproxy:
    image: mariadb:latest
    container_name: dbproxy
    restart: always
    networks:
      - media-stack
    environment:
      MYSQL_ROOT_PASSWORD: "proxyroot"
      MYSQL_DATABASE: "proxydb"
      MYSQL_USER: "proxyuser"
      MYSQL_PASSWORD: "proxypass"
      TZ: "America/Santiago"
    volumes:
      - /opt/proxy-manager/data/mysql:/var/lib/mysql

networks:
  media-stack:
    name: media-stack
