version: '3.7'
services:

  jackett:
    #container_name: jackett
    image:  linuxserver/jackett
    #restart: unless-stopped
    networks:
      - file-stack
    environment:
      - TZ=America/Santiago
      - PLEX_UID=0
      - PLEX_GUID=0
    volumes:
      - /opt/jackett:/config
      - /mnt/multimedia:/mnt/multimedia
      - /mnt/download:/downloads
    ports:
      - 9117:9117
        
  
  #deluge
  deluge:
    #container_name: deluge
    image: linuxserver/deluge
    #restart: unless-stopped
    networks:
      - file-stack
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Santiago
    volumes:
      - /opt/deluge-docker:/config
      - /mnt/multimedia:/mnt/multimedia
      - /mnt/download:/downloads
    ports:
      - 8112:8112
      
  # filebrowser
  filebrowser:
    #container_name: filebrowser
    image: filebrowser/filebrowser
    #restart: unless-stopped
    networks:
      - file-stack
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Santiago
    volumes:
      - /opt/filebrowser:/data
      - /mnt/multimedia:/mnt/multimedia
    ports:
      - 89:80

    
networks:
  file-stack:
    name: file-stack
